[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = "--spec"
spec_test_format = "{result} {docstring_summary}"

[coverage:run]
omit =
    tests/*
    front_end-demo/*